/*
 * Copyright 2026 Duck Apps Contributor
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.eltavine.duckdetector.features.dashboard.data

import com.eltavine.duckdetector.BuildConfig
import com.eltavine.duckdetector.core.ui.model.DetectionSeverity
import com.eltavine.duckdetector.core.ui.presentation.formatBuildTimeUtc
import com.eltavine.duckdetector.features.bootloader.ui.model.BootloaderCardModel
import com.eltavine.duckdetector.features.customrom.ui.model.CustomRomCardModel
import com.eltavine.duckdetector.features.dangerousapps.ui.model.DangerousAppsCardModel
import com.eltavine.duckdetector.features.dashboard.ui.model.DashboardDetectorCardEntry
import com.eltavine.duckdetector.features.dashboard.ui.model.DashboardUiState
import com.eltavine.duckdetector.features.deviceinfo.ui.model.DeviceInfoCardModel
import com.eltavine.duckdetector.features.kernelcheck.ui.model.KernelCheckCardModel
import com.eltavine.duckdetector.features.lsposed.ui.model.LSPosedCardModel
import com.eltavine.duckdetector.features.memory.ui.model.MemoryCardModel
import com.eltavine.duckdetector.features.mount.ui.model.MountCardModel
import com.eltavine.duckdetector.features.nativeroot.ui.model.NativeRootCardModel
import com.eltavine.duckdetector.features.playintegrityfix.ui.model.PlayIntegrityFixCardModel
import com.eltavine.duckdetector.features.selinux.ui.model.SelinuxCardModel
import com.eltavine.duckdetector.features.su.ui.model.SuCardModel
import com.eltavine.duckdetector.features.systemproperties.ui.model.SystemPropertiesCardModel
import com.eltavine.duckdetector.features.tee.ui.model.TeeCardModel
import com.eltavine.duckdetector.features.virtualization.ui.model.VirtualizationCardModel
import com.eltavine.duckdetector.features.zygisk.ui.model.ZygiskCardModel
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class DashboardExportFormatter {

    fun format(state: DashboardUiState): String = buildString {
        val now = SimpleDateFormat("yyyy-MM-dd HH:mm:ss (z)", Locale.US).format(Date())

        appendLine("# Duck Detector — Security Scan Report")
        appendLine()
        appendLine("| Item | Value |")
        appendLine("|------|-------|")
        appendLine("| App Version | ${BuildConfig.VERSION_NAME} (${BuildConfig.VERSION_CODE}) |")
        appendLine("| Build Hash | ${BuildConfig.BUILD_HASH} |")
        appendLine("| Build Time | ${formatBuildTimeUtc(BuildConfig.BUILD_TIME_UTC)} (UTC) |")
        appendLine("| Report Time | $now |")
        appendLine()

        appendLine("## Overview")
        appendLine()
        appendLine("> **${state.overview.headline}** — ${state.overview.summary}")
        appendLine()
        appendLine("| Danger | Warning | Ready | Pending |")
        appendLine("|--------|---------|-------|---------|")
        val danger = state.overview.metrics.find { it.label == "Danger" }?.value ?: "0"
        val warning = state.overview.metrics.find { it.label == "Warning" }?.value ?: "0"
        val ready = state.overview.metrics.find { it.label == "Ready" }?.value ?: "0"
        val pending = state.overview.metrics.find { it.label == "Pending" }?.value ?: "0"
        appendLine("| $danger | $warning | $ready | $pending |")
        appendLine()

        appendLine("## Detector Cards")
        appendLine()
        state.detectorCards.forEach { entry ->
            appendDetectorCard(entry)
        }

        appendLine("## Device Info")
        appendLine()
        appendDeviceInfo(state.deviceInfoCard)
        appendLine()

        appendLine("---")
        appendLine("*Report generated by Duck Detector v${BuildConfig.VERSION_NAME}*")
    }

    private fun StringBuilder.appendDetectorCard(entry: DashboardDetectorCardEntry) {
        when (entry) {
            is DashboardDetectorCardEntry.Bootloader -> appendBootloader(entry.model)
            is DashboardDetectorCardEntry.Mount -> appendMount(entry.model)
            is DashboardDetectorCardEntry.CustomRom -> appendCustomRom(entry.model)
            is DashboardDetectorCardEntry.Selinux -> appendSelinux(entry.model)
            is DashboardDetectorCardEntry.DangerousApps -> appendDangerousApps(entry.model)
            is DashboardDetectorCardEntry.KernelCheck -> appendKernelCheck(entry.model)
            is DashboardDetectorCardEntry.Memory -> appendMemory(entry.model)
            is DashboardDetectorCardEntry.LSPosed -> appendLSPosed(entry.model)
            is DashboardDetectorCardEntry.NativeRoot -> appendNativeRoot(entry.model)
            is DashboardDetectorCardEntry.PlayIntegrityFix -> appendPlayIntegrityFix(entry.model)
            is DashboardDetectorCardEntry.Tee -> appendTee(entry.model)
            is DashboardDetectorCardEntry.Su -> appendSu(entry.model)
            is DashboardDetectorCardEntry.SystemProperties -> appendSystemProperties(entry.model)
            is DashboardDetectorCardEntry.Virtualization -> appendVirtualization(entry.model)
            is DashboardDetectorCardEntry.Zygisk -> appendZygisk(entry.model)
        }
    }

    private val String.mdEscape: String get() = replace("|", "\\|").replace("\n", " ")

    private fun severityBadge(severity: DetectionSeverity): String = when (severity) {
        DetectionSeverity.DANGER -> "🔴 DANGER"
        DetectionSeverity.WARNING -> "🟡 WARNING"
        DetectionSeverity.INFO -> "🔵 INFO"
        DetectionSeverity.ALL_CLEAR -> "🟢 CLEAR"
    }

    private fun StringBuilder.appendCardHeader(
        title: String,
        verdict: String,
        severity: DetectionSeverity,
    ) {
        appendLine("### ${severityBadge(severity)} — $title")
        appendLine()
        appendLine("> **Verdict:** ${verdict.mdEscape}")
        appendLine()
    }

    private fun StringBuilder.appendFactsTable(facts: List<Pair<String, String>>) {
        if (facts.isEmpty()) return
        appendLine("| Key | Value |")
        appendLine("|-----|-------|")
        facts.forEach { (label, value) ->
            appendLine("| ${label.mdEscape} | ${value.mdEscape} |")
        }
        appendLine()
    }

    private fun StringBuilder.appendDetailTable(
        rows: List<Triple<String, String, String?>>,
    ) {
        if (rows.isEmpty()) return
        appendLine("| Item | Result | Detail |")
        appendLine("|------|--------|--------|")
        rows.forEach { (label, value, detail) ->
            val detailStr = if (!detail.isNullOrBlank() && detail != value) detail.mdEscape else ""
            appendLine("| ${label.mdEscape} | ${value.mdEscape} | $detailStr |")
        }
        appendLine()
    }

    private fun StringBuilder.appendImpactItems(items: List<String>) {
        if (items.isEmpty()) return
        items.forEach { text ->
            appendLine("- ${text.mdEscape}")
        }
        appendLine()
    }

    private fun headerFactsToPairs(facts: List<*>): List<Pair<String, String>> {
        return try {
            @Suppress("UNCHECKED_CAST")
            facts.map { fact ->
                val label =
                    fact!!::class.java.getDeclaredField("label").apply { isAccessible = true }.get(fact) as String
                val value =
                    fact!!::class.java.getDeclaredField("value").apply { isAccessible = true }.get(fact) as String
                label to value
            }
        } catch (_: Exception) {
            emptyList()
        }
    }

    private fun detailRowsToTriples(rows: List<*>): List<Triple<String, String, String?>> {
        return try {
            @Suppress("UNCHECKED_CAST")
            rows.map { row ->
                val label =
                    row!!::class.java.getDeclaredField("label").apply { isAccessible = true }.get(row) as String
                val value =
                    row!!::class.java.getDeclaredField("value").apply { isAccessible = true }.get(row) as String
                val detail = try {
                    row::class.java.getDeclaredField("detail").apply { isAccessible = true }.get(row) as? String
                } catch (_: Exception) {
                    null
                }
                Triple(label, value, detail)
            }
        } catch (_: Exception) {
            emptyList()
        }
    }

    private fun impactItemsToStrings(items: List<*>): List<String> {
        return try {
            @Suppress("UNCHECKED_CAST")
            items.map { item ->
                item!!::class.java.getDeclaredField("text").apply { isAccessible = true }.get(item) as String
            }
        } catch (_: Exception) {
            emptyList()
        }
    }

    private fun StringBuilder.appendSectionTitle(title: String, isEmpty: Boolean) {
        if (isEmpty) return
        appendLine("**$title**")
        appendLine()
    }

    private fun StringBuilder.appendBootloader(model: BootloaderCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        appendSectionTitle("State", model.stateRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.stateRows))
        appendSectionTitle("Attestation", model.attestationRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.attestationRows))
        appendSectionTitle("Properties", model.propertyRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.propertyRows))
        appendSectionTitle("Consistency", model.consistencyRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.consistencyRows))
        appendSectionTitle("Methods", model.methodRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.methodRows))
        appendSectionTitle("Scan", model.scanRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.scanRows))
        if (model.impactItems.isNotEmpty()) {
            appendLine("**Impact**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.impactItems))
        }
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendMount(model: MountCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        appendSectionTitle("Artifacts", model.artifactRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.artifactRows))
        appendSectionTitle("Runtime", model.runtimeRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.runtimeRows))
        appendSectionTitle("Filesystem", model.filesystemRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.filesystemRows))
        appendSectionTitle("Consistency", model.consistencyRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.consistencyRows))
        appendSectionTitle("Methods", model.methodRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.methodRows))
        appendSectionTitle("Scan", model.scanRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.scanRows))
        if (model.impactItems.isNotEmpty()) {
            appendLine("**Impact**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.impactItems))
        }
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendCustomRom(model: CustomRomCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        appendSectionTitle("Build", model.buildRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.buildRows))
        appendSectionTitle("Runtime", model.runtimeRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.runtimeRows))
        appendSectionTitle("Framework", model.frameworkRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.frameworkRows))
        appendSectionTitle("Methods", model.methodRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.methodRows))
        appendSectionTitle("Scan", model.scanRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.scanRows))
        if (model.impactItems.isNotEmpty()) {
            appendLine("**Impact**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.impactItems))
        }
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendSelinux(model: SelinuxCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        appendSectionTitle("State", model.stateRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.stateRows))
        appendSectionTitle("Policy", model.policyRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.policyRows))
        appendSectionTitle("Audit", model.auditRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.auditRows))
        appendSectionTitle("Device", model.deviceRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.deviceRows))
        appendSectionTitle("Methods", model.methodRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.methodRows))
        if (model.impactItems.isNotEmpty()) {
            appendLine("**Impact**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.impactItems))
        }
        if (model.policyNotes.isNotEmpty()) {
            appendLine("**Policy Notes**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.policyNotes))
        }
        if (model.auditNotes.isNotEmpty()) {
            appendLine("**Audit Notes**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.auditNotes))
        }
        if (model.references.isNotEmpty()) {
            appendLine("**References**")
            appendLine()
            model.references.forEach { ref -> appendLine("- $ref") }
            appendLine()
        }
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendDangerousApps(model: DangerousAppsCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        if (model.hmaAlert != null) {
            appendLine("**HMA Alert:** ${model.hmaAlert.title}")
            appendLine()
            appendLine("> ${model.hmaAlert.summary}")
            appendLine()
            if (model.hmaAlert.hiddenPackages.isNotEmpty()) {
                appendLine("| App | Package | Methods |")
                appendLine("|-----|---------|---------|")
                model.hmaAlert.hiddenPackages.forEach { pkg ->
                    appendLine("| ${pkg.appName} | ${pkg.packageName} | ${pkg.methods.joinToString(", ")} |")
                }
                appendLine()
            }
        }
        if (model.packageItems.isNotEmpty()) {
            appendLine("**Suspicious Packages**")
            appendLine()
            appendLine("| App | Package | Methods |")
            appendLine("|-----|---------|---------|")
            model.packageItems.forEach { pkg ->
                appendLine("| ${pkg.appName} | ${pkg.packageName} | ${pkg.methods.joinToString(", ")} |")
            }
            appendLine()
        }
        if (model.context.isNotEmpty()) {
            appendLine("**Context**")
            appendLine()
            model.context.forEach { ctx ->
                appendLine("- **${ctx.label}:** ${ctx.value}")
            }
            appendLine()
        }
        if (model.targetApps.isNotEmpty()) {
            appendLine("**Target Apps**")
            appendLine()
            appendLine("| App | Package | Category |")
            appendLine("|-----|---------|----------|")
            model.targetApps.forEach { app ->
                appendLine("| ${app.appName} | ${app.packageName} | ${app.category} |")
            }
            appendLine()
        }
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendKernelCheck(model: KernelCheckCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        appendSectionTitle("Identity", model.identityRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.identityRows))
        appendSectionTitle("Anomalies", model.anomalyRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.anomalyRows))
        appendSectionTitle("Behavior", model.behaviorRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.behaviorRows))
        appendSectionTitle("Methods", model.methodRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.methodRows))
        appendSectionTitle("Scan", model.scanRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.scanRows))
        if (model.impactItems.isNotEmpty()) {
            appendLine("**Impact**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.impactItems))
        }
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendMemory(model: MemoryCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        appendSectionTitle("Hooks", model.hookRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.hookRows))
        appendSectionTitle("Mapping", model.mappingRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.mappingRows))
        appendSectionTitle("Loader", model.loaderRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.loaderRows))
        appendSectionTitle("Methods", model.methodRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.methodRows))
        appendSectionTitle("Scan", model.scanRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.scanRows))
        if (model.impactItems.isNotEmpty()) {
            appendLine("**Impact**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.impactItems))
        }
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendLSPosed(model: LSPosedCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        appendSectionTitle("Runtime", model.runtimeRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.runtimeRows))
        appendSectionTitle("Binder", model.binderRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.binderRows))
        appendSectionTitle("Package", model.packageRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.packageRows))
        appendSectionTitle("Native", model.nativeRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.nativeRows))
        appendSectionTitle("Methods", model.methodRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.methodRows))
        appendSectionTitle("Scan", model.scanRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.scanRows))
        if (model.impactItems.isNotEmpty()) {
            appendLine("**Impact**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.impactItems))
        }
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendNativeRoot(model: NativeRootCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        appendSectionTitle("Native", model.nativeRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.nativeRows))
        appendSectionTitle("Runtime", model.runtimeRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.runtimeRows))
        appendSectionTitle("Kernel", model.kernelRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.kernelRows))
        appendSectionTitle("Properties", model.propertyRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.propertyRows))
        appendSectionTitle("Methods", model.methodRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.methodRows))
        appendSectionTitle("Scan", model.scanRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.scanRows))
        if (model.impactItems.isNotEmpty()) {
            appendLine("**Impact**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.impactItems))
        }
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendPlayIntegrityFix(model: PlayIntegrityFixCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        appendSectionTitle("Properties", model.propertyRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.propertyRows))
        appendSectionTitle("Consistency", model.consistencyRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.consistencyRows))
        appendSectionTitle("Native", model.nativeRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.nativeRows))
        appendSectionTitle("Methods", model.methodRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.methodRows))
        appendSectionTitle("Scan", model.scanRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.scanRows))
        if (model.impactItems.isNotEmpty()) {
            appendLine("**Impact**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.impactItems))
        }
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendTee(model: TeeCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        if (model.highlightSignals.isNotEmpty()) {
            appendLine("**Highlight Signals**")
            appendLine()
            appendLine("| Signal | Value |")
            appendLine("|--------|-------|")
            model.highlightSignals.forEach { signal ->
                appendLine("| ${signal.label} | ${signal.value} |")
            }
            appendLine()
        }
        model.factGroups.forEach { group ->
            appendLine("**${group.title}**")
            appendLine()
            appendLine("| Item | Value |")
            appendLine("|------|-------|")
            group.rows.forEach { row ->
                appendLine("| ${row.label} | ${row.value} |")
            }
            appendLine()
        }
        appendLine("- **Network:** ${model.networkState.summary}")
        appendLine("- **Certificate Count:** ${model.certificateSummary.count}")
        if (model.exportText.isNotBlank()) {
            appendLine()
            appendLine("<details>")
            appendLine("<summary>TEE Detailed Export</summary>")
            appendLine()
            appendLine("```")
            appendLine(model.exportText)
            appendLine("```")
            appendLine("</details>")
        }
        appendLine()
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendSu(model: SuCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        appendSectionTitle("Artifacts", model.artifactRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.artifactRows))
        appendSectionTitle("Context", model.contextRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.contextRows))
        appendSectionTitle("Methods", model.methodRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.methodRows))
        appendSectionTitle("Scan", model.scanRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.scanRows))
        if (model.impactItems.isNotEmpty()) {
            appendLine("**Impact**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.impactItems))
        }
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendSystemProperties(model: SystemPropertiesCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        appendSectionTitle("Core", model.coreRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.coreRows))
        appendSectionTitle("Boot", model.bootRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.bootRows))
        appendSectionTitle("Build", model.buildRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.buildRows))
        appendSectionTitle("Source", model.sourceRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.sourceRows))
        appendSectionTitle("Consistency", model.consistencyRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.consistencyRows))
        appendSectionTitle("Info", model.infoRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.infoRows))
        appendSectionTitle("Methods", model.methodRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.methodRows))
        appendSectionTitle("Scan", model.scanRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.scanRows))
        if (model.impactItems.isNotEmpty()) {
            appendLine("**Impact**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.impactItems))
        }
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendVirtualization(model: VirtualizationCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        appendSectionTitle("Environment", model.environmentRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.environmentRows))
        appendSectionTitle("Runtime", model.runtimeRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.runtimeRows))
        appendSectionTitle("Consistency", model.consistencyRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.consistencyRows))
        appendSectionTitle("Honeypot", model.honeypotRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.honeypotRows))
        appendSectionTitle("Host Apps", model.hostAppRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.hostAppRows))
        appendSectionTitle("Methods", model.methodRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.methodRows))
        appendSectionTitle("Scan", model.scanRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.scanRows))
        if (model.impactItems.isNotEmpty()) {
            appendLine("**Impact**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.impactItems))
        }
        if (model.references.isNotEmpty()) {
            appendLine("**References**")
            appendLine()
            model.references.forEach { ref -> appendLine("- $ref") }
            appendLine()
        }
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendZygisk(model: ZygiskCardModel) {
        appendCardHeader(model.title, model.verdict, model.status.severity)
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        appendSectionTitle("State", model.stateRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.stateRows))
        appendSectionTitle("Signals", model.signalRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.signalRows))
        appendSectionTitle("Methods", model.methodRows.isEmpty())
        appendDetailTable(detailRowsToTriples(model.methodRows))
        if (model.impactItems.isNotEmpty()) {
            appendLine("**Impact**")
            appendLine()
            appendImpactItems(impactItemsToStrings(model.impactItems))
        }
        if (model.references.isNotEmpty()) {
            appendLine("**References**")
            appendLine()
            model.references.forEach { ref -> appendLine("- $ref") }
            appendLine()
        }
        appendLine("---")
        appendLine()
    }

    private fun StringBuilder.appendDeviceInfo(model: DeviceInfoCardModel) {
        appendLine("### ${model.title}")
        appendLine()
        appendLine("> ${model.verdict}")
        appendLine()
        appendFactsTable(headerFactsToPairs(model.headerFacts))
        model.sections.forEach { section ->
            appendLine("**${section.title}**")
            appendLine()
            appendLine("| Key | Value |")
            appendLine("|-----|-------|")
            section.rows.forEach { row ->
                appendLine("| ${row.label} | ${row.value} |")
            }
            appendLine()
        }
    }
}
